### ISSUE TITLE
Adding Resize and crop options for Image picker

### ISSUE THREAD

**Issue by georgefam** [EurekaCommunity/ImageRow#10]
Is it possible to add a new feature to enable crop and resize selected pictures ? thanks

**Comment by mats-claassen** [comment]
I think the correct way to support this is to change the ImagePickerController and implementing it yourself.
You should be able to subclass `ImagePickerController` to implement that feature and then set `presentationMode` of your row to instantiate your subclass of ImagePickerController.

When you set `presentationMode` you should do something similar to what is done currently in `_ImageRow` at https://github.com/EurekaCommunity/ImageRow/blob/master/Sources/ImageRow.swift#L80-L83

Tell me if this works for you.

**Comment by ninasaveljeva** [comment]
I have same problem. Can you give some code examples? I want to integrated third-party cropping library (https://github.com/IGRSoft/IGRPhotoTweaks) to ImageRow, so user could select and crop image.
