### ISSUE TITLE
Image not changing

### ISSUE THREAD

**Issue by luizbim** [EurekaCommunity/ImageRow#11]
Hi I have a swift 3 project and I'm trying to use ImageRow but image at row does not change when I select a picture in photo library.
Besides this The error: "[Generic] Creating an image format with an unknown type is an error" is showing up. I have tryed the solution presented in issue https://github.com/EurekaCommunity/ImageRow/issues/7 but not worked for me.

my code is:
````
<<< ImageRow(){ row in
   row.title = "Challenge Image"
   row.sourceTypes = [.PhotoLibrary, .SavedPhotosAlbum, .Camera]
   row.clearAction = .yes(style: UIAlertActionStyle.destructive)
   if nil != self.myobj.img {
      row.value = UIImage(named: self.myobj.img!)
   } else {
      row.value = UIImage(named: "default-img")
   }
}
````

**Comment by garymansted** [comment]
Any luck? Im having the same issue.

**Comment by mats-claassen** [comment]
Running the examples, I am seeing the error message in the console but the images update always. Are you sure you are not doing anything else with the ImageRow that might cause this? The issue should not be in the code you posted.

**Comment by chefren** [comment]
I am seeing a problem with the image not displaying, when the ImageRow is within a MultiValuedSection, it seems that this sections affects the cell somehow.

I added a [branch on my Eureka repo fork](https://github.com/chefren/Eureka/commit/2ba370516c4c6502b906c4ba1a9b8978d83dd781) to easily see this on the Demo App

**Comment by santiagofm** [comment]
Hey @chefren ! This issue was fixed in https://github.com/EurekaCommunity/ImageRow/pull/14.
Please point your pod to the master branch until we release a new build.
Closing this issue also.
Cheers

**Comment by chefren** [comment]
Thanks Santiago!
