### ISSUE TITLE
How to display the image other than as an accessory view?

### ISSUE THREAD

**Issue by everestman27** [EurekaCommunity/ImageRow#12]
I wanted to check if the imageRow can be customized for the below 2 scenarios. If so, looking to understand how to customize it so that I can take advantage of the ImagePickerController that comes with it.

1) Profile image that is displayed in the center of a cell
    Here is what I tried:  I figured out how to do sub-class a Cell and Row and use a cellProvider to call a .xib file that has imageview in center, however, missing how to create a "image picker" feature.

2) An collection view within the imageRow that contains one cell per image added from image source (camera/photo library) and a default "+" imageview collectionview cell that when clicked presents the ImagePickerController. This is for ability to show multiple pictures added horizontally and be able to clear an added picture by tap on an existing picture

Thanks in advance

**Comment by mats-claassen** [comment]
Currently the ImageRow is tied to the `SelectorCell` which in Eureka 2.0.1 cannot be instantiated from a nib file. I think the `ImageRow` needs a revamp to let it be designed on a nib file. This would also allow the second scenario but in that case I think that there will be a lot of logic that you will have to implement to handle the collectionView.

What do you think @mtnbarreto?

**Comment by chefren** [comment]
For the second scenario I did something similar by using the MultivaluedSection, and the Add Button simply adds an ImageRow, which then can be used independently. I am still trying to figure out how to add intermediate steps for the scenario I need.

Mathias, how different is it from the updated (tag:2.0.0) ImageRow, the revamp you mention to allow nib file design? It seems that tag's example has that, in `MyImageRow`, right?
And another question, to be able to modify the Picker options for eg. to add a "View" option, is the best way to add an Action similar to the existing `clearAction` (ie: would need more code in _ImageRow)?

Thanks!

**Comment by mats-claassen** [comment]
So version 2.0.0 does include support for Eureka 3.0 and it also makes it easier to use nib files for custom cells. This should make it easier to add a collection view to the cell. (It is in the examples as you said)

To add or modify the actions of the ActionSheet you will have to override the `customDidSelect`. I think this part should be more customizable, in that it should be easy to modify those actions. Maybe `createOptionsForAlertController` should be open or we should divide `customDidSelect` in multiple overridable functions.

**Comment by chefren** [comment]
Thanks Mathias for the feedback and those interesting ideas!
