### ISSUE TITLE
Change status bar color

### ISSUE THREAD

**Issue by edoardodc** [EurekaCommunity/ImageRow#20]
Is there any way to change the current status bar style to `default`? Looks like the image picker is using the status bar style that my app is using, even though this doesn't look nice. 

Thanks!

![simulator screen shot 10 lug 2017 12 00 15](https://user-images.githubusercontent.com/14259817/28012891-8bb7dd38-6567-11e7-906c-44c42b33b7b1.png)

**Comment by csr** [comment]
+1

**Comment by csr** [comment]
@mats-claassen would love if you could look into this please.

**Comment by V-FEXrt** [comment]
@JimboPower 

This should work as long as you _haven't_ set **View controller-based status bar appearance** to **no** in your info.plist file

https://gist.github.com/V-FEXrt/87367a1dbb4485b7907c2eca849ad76b
