### ISSUE TITLE
ImageRow.podspec needs to update

### ISSUE THREAD

**Issue by allenhuang** [EurekaCommunity/ImageRow#22]
Eureka moves to 3.1.0 while ImageRow(2.0.0) still depends on 3.0 tightly.
Suggestion to revise

> s.dependency 'Eureka', '> 3.0'

**Comment by TCOA** [comment]
Please get this moved - with Swift 4 my apps now won't compile!

See https://github.com/xmartlabs/Eureka/issues/1220 for error messages and what I've tried.

**Comment by mtnbarreto** [comment]
done!
