### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by danielbrutti** [EurekaCommunity/ImageRow#23]
Hello,

Just want to let you know it would be good to include in the README that [NSCameraUsageDescription](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW24) is necessary in **Info.plist** when trying to work with Camera.

For rookies like me on iOS and Swift development would be a good information :)

Thanks!

**Comment by mtnbarreto** [comment]
@danielbrutti  Could you please update the readme?
