### ISSUE TITLE
ImageRow.swift:72:71: Generic type 'SelectorRow' specialized with too many type parameters (got 2, but expected 1)

### ISSUE THREAD

**Issue by anandramv** [EurekaCommunity/ImageRow#24]
I am trying to import the Image row and use Eureka 3.1.0. I am getting a strange error in the below specified line:
`open class _ImageRow<VCType: TypedRowControllerType, Cell: CellType>: SelectorRow<Cell, VCType>, ImageRowProtocol where VCType: UIImagePickerController, VCType.RowValue == UIImage, Cell: BaseCell, Cell: TypedCellType, Cell.Value == UIImage`

Error is: ..../ImageRow/ImageRow.swift:72:71: Generic type 'SelectorRow' specialized with too many type parameters (got 2, but expected 1)

can you please help to resolve this issue?

**Comment by StriderHND** [comment]
I Think the is related to Swift 4 upgrade

**Comment by mtnbarreto** [comment]
I just release a new ImageRow version which is compatible with Eureka ~> 4.0
use ImageRow 3.0.0 with Eureka ~>4.0 as requirements indicates.
