### ISSUE TITLE
Question: Is there a way to get the image path of the chosen image?

### ISSUE THREAD

**Issue by andorfermichael** [EurekaCommunity/ImageRow#26]
Hey,

I was wondering if there is a quick way to get the image path of the selected image.

Thanks in advance.

**Comment by mtnbarreto** [comment]
imageRow.imageURL does the trick. https://github.com/EurekaCommunity/ImageRow/blob/ad772c9b5923138db6bbdeb1d57e7ff19bee8568/Sources/ImageRow.swift#L77
