### ISSUE TITLE
Add Eureka 4.0 Support in CocoaPods

### ISSUE THREAD

**Issue by uetcis** [EurekaCommunity/ImageRow#28]
Now, I get this error while doing pod install
```
[!] Unable to satisfy the following requirements:

- `Eureka (~> 4.0.0)` required by `Podfile`
- `Eureka (= 3.0)` required by `ImageRow (2.0.0)`
```

**Comment by TCOA** [comment]
similar to https://github.com/xmartlabs/Eureka/issues/1220#issuecomment-332392488

in https://github.com/xmartlabs/Eureka/issues/1266 #mtnbarreto said to use 4.0.1, though it does the same thing.......

Certainly there should be a fix - or consistency between the programs - somewhere.....

I've been struggling with all this mess off/on for two weeks and still getting 'progress' - much higher wasted time, high levels of frustration and further behind on my delivery of my app!

**Comment by mtnbarreto** [comment]
Done!, ImageRow 3.0.0 is compatible with Eureka ~> 4.0
