### ISSUE TITLE
Custom Cell Class

### ISSUE THREAD

**Issue by dev4dev** [EurekaCommunity/ImageRow#3]
Hello guys,

Thanks for such a great component. But it's a little bit too complex to grasp it quickly. Can you help with custom cell class, where I can have imageView added to contentView, and not sticked to accessoryView position.

I ended up with something like this

```swift
protocol ImagePickerCellType: class {
	var imagePickerView: UIImageView! { get set }
}

public class ImagePickerCell: Cell<UIImage>, CellType, ImagePickerCellType {

	internal(set) var imagePickerView: UIImageView!

	public override func setup() {
		super.setup()
		imagePickerView = UIImageView(frame: .init(x: 200, y: 0, width: 44.0, height: 44.0))
		imagePickerView.contentMode = .scaleAspectFill
		imagePickerView.clipsToBounds = true
		contentView.addSubview(imagePickerView)
	}

	public override func update() {
		super.update()
		accessoryType = .disclosureIndicator
		editingAccessoryType = accessoryType
		selectionStyle = row.isDisabled ? .none : .default
	}
}
```

Therefore I don't know how to setup Cell constraint in Row definition. I tried to add **Cell: ImagePickerCellType** to `open class _ImageRow<Cell: CellType>: SelectorRow<Cell, ImagePickerController> where Cell: BaseCell,  Cell.Value == UIImage {`, but I got `Generic class cannot be declared  because its generic requirement uses an internal type`.

As temporary solution I updated row as follow

```swift
open override func customUpdateCell() {
        super.customUpdateCell()
        cell.accessoryType = .none

		guard let cell = cell as? ImagePickerCellType else { return }

        if let image = self.value {
            cell.imagePickerView.image = image
        } else {
            cell.imagePickerView.image = nil
        }
    }
```

**Comment by mats-claassen** [comment]
The error `Generic class cannot be declared because its generic requirement uses an internal type` you are getting is because some class or protocol you use is not declared public. 
Try declaring `ImagePickerCellType` as public

**Comment by dev4dev** [comment]
Omg...that's so simple...

Thank you, now everything is ok! 🎉
