### ISSUE TITLE
UIImagePickerController not localized

### ISSUE THREAD

**Issue by Kater--S** [EurekaCommunity/ImageRow#35]
On an iPhone localized in German, I use ImageRow with a Localizable.string file as described in README.md, containing translations for all English UI texts. The actionsheet is correctly shown in German, but when I enter camera mode, I see "PHOTO", "Cancel", "Retake", "Use Photo" in English. In photo library / saved photos, heading and section titles are German, but the "Cancel" button isn't.

![img_2950](https://user-images.githubusercontent.com/10419591/34524740-ead97874-f09c-11e7-9e63-1df803ebc9ab.PNG)
![img_2951](https://user-images.githubusercontent.com/10419591/34524741-eaf94f78-f09c-11e7-94de-80d3bd3eedd8.PNG)
![img_2944](https://user-images.githubusercontent.com/10419591/34524742-eb1cd5ba-f09c-11e7-94eb-25800941cd49.PNG)
![img_2945](https://user-images.githubusercontent.com/10419591/34524743-eb6391b2-f09c-11e7-9665-a27be0ee8d42.PNG)

**Comment by joaodforce** [comment]
the UIImagePickerController is managed by the system.
Only the action sheet can be localized.

**Comment by Kater--S** [comment]
Any idea how I can force the camera menu to German, other than having German globally set as the system's UI language? Are there any app-specific settings?

**Comment by joaodforce** [comment]
According to the Apple Docs, it doesn't seem like you can.

https://developer.apple.com/documentation/uikit/uiimagepickercontroller

The only solution for you to do that, would disable the standard controls and create your own overlay, but I don't think you have enough control over the UIImagePickerController to do that with ImageRow, you would have to customize it, or create your own custom Row.

**Comment by Kater--S** [comment]
Ok, but in other apps (Apple's own Camera app as well as other 3rd party apps) the UI is shown in German (i.e. according to my global language settings). There must be a way to achieve this here also.

**Comment by Kater--S** [comment]
Sorry, my fault. Despite having German UI my app was not localized (because not needed in that project), therefor per default seen as English ⇒ English UI in system dialogs.

**Comment by amadeu01** [comment]
@Kater--S 

I "fixed" this by swizzling the methods of bundle

```
private func swizzle(_ bundle: Bundle.Type) {

    [(#selector(bundle.localizedString(forKey:value:table:)),
      #selector(bundle. custom_localizedString(forKey:value:table:)))]
        .forEach { original, swizzled in

            guard let originalMethod = class_getInstanceMethod(bundle, original),
                let swizzledMethod = class_getInstanceMethod(bundle, swizzled) else { return }

            let didAddViewDidLoadMethod = class_addMethod(bundle,
                                                          original,
                                                          method_getImplementation(swizzledMethod),
                                                          method_getTypeEncoding(swizzledMethod))

            if didAddViewDidLoadMethod {
                class_replaceMethod(bundle,
                                    swizzled,
                                    method_getImplementation(originalMethod),
                                    method_getTypeEncoding(originalMethod))
            } else {
                method_exchangeImplementations(originalMethod, swizzledMethod)
            }
    }
}

private var hasSwizzled = false

extension Bundle {
    final public class func
        doBadSwizzleStuff() {
        guard !hasSwizzled else { return }

        hasSwizzled = true
        swizzle(self)

    }

    @objc internal func custom_localizedString(forKey: String, value: String?, table: String?) -> String {
        let bundle = Bundle.main
        return bundle.rd_localizedString(forKey: forKey, value: value, table: table)
    }
}
```

then, I created a file `CameraUI.strings` with the localised strings.

```
"PHOTO" = "PHOTO";
"AEAF_LOCK_TEXT" = "AE/AF LOCK";
"API_CANCEL_TITLE" = "Cancel";
"HDR_AUTO" = "Auto";
"HDR_ON" = "On";
"HDR_OFF" = "Off";
"TIMER_OFF_TEXT" = "Off";
"USE_PHOTO" = "Use test";

```

**Comment by moKelani** [comment]
> swizzling the methods of bundle

when i can call swizzle to apply this location
