### ISSUE TITLE
Add custom camera to Image Picker Controller

### ISSUE THREAD

**Issue by cristianchaparroa** [EurekaCommunity/ImageRow#37]
- Environment: ImageRow
- Xcode: 9.2 (9C40b)

I've created a customer Camera Controller  that extends from  ```UIViewController```, but I don't  how  to set this custom camera when I choose a ```.Camera``` Source Type using the ```ImageRow``` What should I do for that?  

  **Labels:** Help Required

**Comment by mats-claassen** [comment]
You have to override `presentationMode` to return a custom image picker controller. However, the way ImageRow is defined you would possibly have to reimplement `_ImageRow` to be able to push a controller which isn't a subclass of `UIImagePickerController`
