### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by mrfarukturgut** [EurekaCommunity/ImageRow#4]
Hi, I am using Eureka and ImageRow as an addition to it. The master branch is installed with cocoapods. However I have strange thing, maybe it is not strange, I add `.Camera` to `row.sourceTypes` but there is no option about Camera in the `ActionSheet`. Any thoughts? 

```swift
<<< ImageRow() { row in
                row.title = "Picture"
                row.sourceTypes = [.PhotoLibrary, .SavedPhotosAlbum, .Camera]
                row.clearAction = .yes(style: .default)
            }
 
```

**Comment by mats-claassen** [comment]
Hi, sorry for the late response. Were you testing on the Simulator? The simulator has no camera, that's why it won't appear there.
