### ISSUE TITLE
Get multiple imageRows into an imageArray.

### ISSUE THREAD

**Issue by martheli** [EurekaCommunity/ImageRow#45]
I am trying to get the image from the image row and put it into an array. I am using the Eureka multivalued row so I can have multiple photos. I then use the form.values to put everything into a dictionary. The tag for each imageRow starts with "Image" I am trying to take the photos and put them into a photos array like this:

 if key.hasPrefix("Image") {
                    newReport.images?.append((value)! as! UIImage)
               }

I try to print out the array just to see if my images are in there and the array shows as nil. Am I supposed to do anything different to get the image from an imageRow? Am I correct to assume it should return a UIImage for each row?

**Comment by mats-claassen** [comment]
I am only guessing but are you instantiating the array somewhere? If not then `newReport.images?.append(...)` does not do anything.

**Comment by martheli** [comment]
Yes, I have an object called Report that has an array of UIImages called images. I create the object with:

 var newReport = Report()

Then I am trying to append the images that I get from the imageRow.

**Comment by philiprenich** [comment]
@martheli How did you end up solving this? Could you show some code examples? I am going to have the same use case I believe.
