### ISSUE TITLE
Xcode 10 and Swift 4.2

### ISSUE THREAD

**Issue by TofPlay** [EurekaCommunity/ImageRow#46]
Issues when we build ImageRow with Xcode 10 Beta 6 and Swift 4.2

![image](https://user-images.githubusercontent.com/1082222/44925202-0b185b00-ad4e-11e8-90fe-caf7fd41b4b6.png)

I know that Xcode 10 still in beta but the date of the Keynote is approaching quickly and if we want our application to be ready when iOS 12 will come out the components we use are ready a little before

**Comment by mats-claassen** [comment]
A Pull Request would be appreciated if somebody fixes this

**Comment by damozhang** [comment]
@TofPlay #48
