### ISSUE TITLE
It gives compiler error

### ISSUE THREAD

**Issue by sahibhussain** [EurekaCommunity/ImageRow#51]
swift gives 11 compiler error when i add ImageRow pod
![screenshot 2018-10-09 at 12 09 02 am](https://user-images.githubusercontent.com/20224571/46627353-db801e00-cb57-11e8-9542-ebc33b7c95a6.png)

**Comment by mats-claassen** [comment]
You have a mismatched Swift version there, i.e. trying to compile with the wrong Swift version.

For Swift 4.2 use the master branch. There is no release for that yet

**Comment by cameronrll** [comment]
Any update when there will be a release for swift 4.2? Or anyway to work around this now?
