### ISSUE TITLE
VideoRow

### ISSUE THREAD

**Issue by Smiller193** [EurekaCommunity/ImageRow#53]
So I am currently working on a videoRow and I am sort of stuck. i have leveraged some of the code from the image row as can be seen below.

    [import Foundation
    import Eureka
    
    public struct VideoRowSourceTypes : OptionSet {
        
        public let rawValue: Int
        public var imagePickerControllerSourceTypeRawValue: Int { return self.rawValue >> 1 }
        
        public init(rawValue: Int) { self.rawValue = rawValue }
        init(_ sourceType: UIImagePickerController.SourceType) { self.init(rawValue: 1 << sourceType.rawValue) }
        
        public static let PhotoLibrary = VideoRowSourceTypes(.photoLibrary)
        public static let All: VideoRowSourceTypes = [PhotoLibrary]
        
    }
    
    extension VideoRowSourceTypes {
        
        // MARK: Helpers
        
        var localizedString: String {
            switch self {
            case VideoRowSourceTypes.PhotoLibrary:
                return "Photo Library"
            default:
                return ""
            }
        }
    }
    
    public enum VideoClearAction {
        case no
        case yes(style: UIAlertAction.Style)
    }
    
    
    
    //MARK: Row
    
    open class VideoRow<Cell: CellType>: OptionsRow<Cell>, PresenterRowType where Cell: BaseCell, Cell.Value == UIImage {
        public typealias PresenterRow = ImagePickerController
    
        /// Defines how the view controller will be presented, pushed, etc.
        open var presentationMode: PresentationMode<PresenterRow>?
        
        /// Will be called before the presentation occurs.
        open var onPresentCallback: ((FormViewController, PresenterRow) -> Void)?
        
        open var sourceTypes: VideoRowSourceTypes = []
    
        open internal(set) var videoURL: URL?
        open var clearAction = VideoClearAction.yes(style: .destructive)
        
        private var _sourceType = UIImagePickerController.SourceType.photoLibrary
        
        public required init(tag: String?) {
            sourceTypes = .All
            super.init(tag: tag)
            presentationMode = .presentModally(controllerProvider: ControllerProvider.callback { return ImagePickerController() }, onDismiss: { [weak self] vc in
                self?.select()
                vc.dismiss(animated: true)
            })
            self.displayValueFor = nil
            
        }
        
        
        // copy over the existing logic from the SelectorRow
        func displayImagePickerController(_ sourceType: UIImagePickerController.SourceType) {
            if let presentationMode = presentationMode, !isDisabled {
                if let controller = presentationMode.makeController(){
                    controller.row = self
                    controller.sourceType = sourceType
                    onPresentCallback?(cell.formViewController()!, controller)
                    presentationMode.present(controller, row: self, presentingController: cell.formViewController()!)
                }
                else{
                    _sourceType = sourceType
                    presentationMode.present(nil, row: self, presentingController: cell.formViewController()!)
                }
            }
        }
        
        
        /// Extends `didSelect` method
        /// Selecting the Image Row cell will open a popup to choose where to source the photo from,
        /// based on the `sourceTypes` configured and the available sources.
        open override func customDidSelect() {
            guard !isDisabled else {
                super.customDidSelect()
                return
            }
            deselect()
            
            var availableSources: VideoRowSourceTypes = []
            
            if UIImagePickerController.isSourceTypeAvailable(.photoLibrary) {
                let _ = availableSources.insert(.PhotoLibrary)
            }
            
            sourceTypes.formIntersection(availableSources)
            
            if sourceTypes.isEmpty {
                super.customDidSelect()
                guard let presentationMode = presentationMode else { return }
                if let controller = presentationMode.makeController() {
                    controller.row = self
                    controller.title = selectorTitle ?? controller.title
                    onPresentCallback?(cell.formViewController()!, controller)
                    presentationMode.present(controller, row: self, presentingController: self.cell.formViewController()!)
                } else {
                    presentationMode.present(nil, row: self, presentingController: self.cell.formViewController()!)
                }
                return
            }
            
            // Now that we know the number of sources aren't empty, let the user select the source
            let sourceActionSheet = UIAlertController(title: nil, message: selectorTitle, preferredStyle: .actionSheet)
            guard let tableView = cell.formViewController()?.tableView  else { fatalError() }
            if let popView = sourceActionSheet.popoverPresentationController {
                popView.sourceView = tableView
                popView.sourceRect = tableView.convert(cell.accessoryView?.frame ?? cell.contentView.frame, from: cell)
            }
            createOptionsForAlertController(sourceActionSheet)
            if case .yes(let style) = clearAction, value != nil {
                let clearPhotoOption = UIAlertAction(title: NSLocalizedString("Clear Photo", comment: ""), style: style, handler: { [weak self] _ in
                    self?.value = nil
                    self?.videoURL = nil
                    self?.updateCell()
                })
                sourceActionSheet.addAction(clearPhotoOption)
            }
            if sourceActionSheet.actions.count == 1 {
                if let imagePickerSourceType = UIImagePickerController.SourceType(rawValue: sourceTypes.imagePickerControllerSourceTypeRawValue) {
                    displayImagePickerController(imagePickerSourceType)
                }
            } else {
                let cancelOption = UIAlertAction(title: NSLocalizedString("Cancel", comment: ""), style: .cancel, handler:nil)
                sourceActionSheet.addAction(cancelOption)
                if let presentingViewController = cell.formViewController() {
                    presentingViewController.present(sourceActionSheet, animated: true)
                }
            }
        }
        
        
        
        
        
        
        }
    
    extension VideoRow {
        //MARK: Helpers
    
        func createOptionsForAlertController(_ alertController: UIAlertController) {
            createOptionForAlertController(alertController, sourceType: .PhotoLibrary)
        }
        
        
        func createOptionForAlertController(_ alertController: UIAlertController, sourceType: VideoRowSourceTypes) {
            guard let pickerSourceType = UIImagePickerController.SourceType(rawValue: sourceType.imagePickerControllerSourceTypeRawValue), sourceTypes.contains(sourceType) else { return }
            let option = UIAlertAction(title: NSLocalizedString(sourceType.localizedString, comment: ""), style: .default, handler: { [weak self] _ in
                self?.displayImagePickerController(pickerSourceType)
            })
            alertController.addAction(option)
        }
    }
        
    
    /// A selector row where the user can pick an image
    public final class _VideoRow : VideoRow<PushSelectorCell<UIImage>>, RowType {
        public required init(tag: String?) {
            super.init(tag: tag)
        }
    }

This is my imagepickercontroller

    import Foundation
    import Eureka
    import MobileCoreServices
    
    /// Selector Controller used to pick an image
    open class ImagePickerController : UIImagePickerController, TypedRowControllerType, UIImagePickerControllerDelegate, UINavigationControllerDelegate {
        
        /// The row that pushed or presented this controller
        public var row: RowOf<UIImage>!
        
        /// A closure to be called when the controller disappears.
        public var onDismissCallback : ((UIViewController) -> ())?
        
        open override func viewDidLoad() {
            super.viewDidLoad()
            delegate = self
            mediaTypes = [kUTTypeMovie as String]
        }
        
    //    open func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any]) {
    //        // The info dictionary may contain multiple representations of the image. You want to use the original.
    //        guard let selectedImage = info[.originalImage] as? UIImage else {
    //            fatalError("Expected a dictionary containing an image, but was provided the following: \(info)")
    //        }
    //
    ////        (row as? _VideoRow)?.videoURL = info[UIImagePickerController.INF] as? URL
    //
    //        onDismissCallback?(self)
    //    }
        
        public func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : Any]) {
            guard let videoURL = info[UIImagePickerControllerMediaURL] as? URL else {
                return
            }
            
            (row as? _VideoRow)?.videoURL = videoURL
            onDismissCallback?(self)
        }
        
        open func imagePickerControllerDidCancel(_ picker: UIImagePickerController){
            onDismissCallback?(self)
        }
    }

Im just trying to figure out
1. Am I on the right track?
2. The ImageRow returns a UIImage what would be the return for the videoRow...the videoURL? if so how would i change the value?
3. How would i change the value but still have a thumbnail for the video appear to represent selected video?

**Comment by SebastianBO** [comment]
https://github.com/EurekaCommunity/ImageRow/issues/33 you've seen this?

**Comment by Smiller193** [comment]
I have completed a video row @SebastianBO

**Comment by Smiller193** [comment]
A little editing to make it look better though. How would i change the title of the imagepickercontroller to only say videos

**Comment by Smiller193** [comment]
only issue currently is that I see don't see videos tile like I typically do. I see videos only after i go into camera roll. If anyone wants to help me we can release this @mats-claassen

**Comment by Smiller193** [comment]
Like i just want to see videos tile like i do here
<img width="686" alt="screen shot 2018-10-17 at 11 34 06 am" src="https://user-images.githubusercontent.com/16108750/47103730-d7b26280-d20d-11e8-9d09-1e5660ad9c88.png">

**Comment by SebastianBO** [comment]
Is this done with the above code? I would like to support with a coffee (patreon) if possible then!

**Comment by Smiller193** [comment]
no it isn't @SebastianBO I am trying to do a google search for how to accomplish this but I can't find anything. And a coffee what do you mean?

**Comment by mats-claassen** [comment]
@Smiller193 Your row does only allow picking videos? Or videos and photos? You could publish it here in EurekaCommunity in a new repository if you want. I can add you to the org.

As for the `value` of the row, this could be an URL for videos, but if we want to extend the functionality to also pick images then it may be better to have an `enum` as value. Or a PHAsset.

**Comment by Smiller193** [comment]
@mats-claassen my row only allows picking of videos.
I also have changed the value to grab the URL and return that instead of an image as well as creating a thumbnail photo to fill the accompanying accessoryView. So all that is done. The only thing i don't like is that when I enter I want there to be an album just for videos like how it is on an iphone. For my mines you must go into the camera roll and there will be the videos which is fine but I would rather it just have a videos tile alone.

**Comment by Smiller193** [comment]
okay so I actually got it to work the way I want it to. It selects videos only. I leveraged some of the code froma custom uiimagepicker to accomplish the goal. Im pretty sure this can be easily extended to support videos and pictures since the return type is phAsset but I only needed videos so I didn't go that far @mats-claassen

**Comment by mats-claassen** [comment]
That sounds very good @Smiller193. Is your row ready to be published? Do you want to publish it here under EurekaCommunity? I just invited you.

**Comment by Smiller193** [comment]
yeah let me just test it real quick with a quick upload to firebase or something to make sure the video is getting added and ill publish it @mats-claassen

**Comment by Smiller193** [comment]
@mats-claassen okay everything works how do i go about publishing it. Like do i make it a pod?
I have never done this tbh

**Comment by mats-claassen** [comment]
First thing is: do you want to leave the repo under your username or should I create a repo like `EurekaCommunity/VideoRow` and you push the code there? This way we keep the custom rows in one place.

Next thing is defining the structure of the project. You might have done this already but it is a good idea to have an example project to show how to use the row. It is also good to have the pod sources in one folder separate from the Example files.
You could have something like this folder structure:
```
Examples/
Sources/
VideoRow.xcworkspace
VideoRow.xcodeproj
```

You will then have to add files like the podspec, README, LICENSE, etc. Have a look at other custom rows like [TableRow](https://github.com/EurekaCommunity/TableRow) or [PostalAddressRow](https://github.com/EurekaCommunity/PostalAddressRow) for a guide.

Then you can push a version to Cocoapods. You can find guides online on how to do this. You will have to register with Cocoapods, add a version tag to your git repo and push it.

If anything else comes up I can help you with that.

**Comment by Smiller193** [comment]
Okay, I'm a little busy at work today but as soon as I get off I will get right to that. Very happy to be helping the community

**Comment by SebastianBO** [comment]
I very much appreciate this! @Smiller193 @mats-claassen

**Comment by SebastianBO** [comment]
Any update on this?

**Comment by Smiller193** [comment]
@SebastianBO ill handle it when I get off work today @mats-claassen  i have just been going through some things im honestly really sorry for holding up the community

**Comment by mats-claassen** [comment]
@Smiller193 I created [this repository](https://github.com/EurekaCommunity/VideoRow) for the VideoRow. You can upload your code there.

**Comment by Smiller193** [comment]
@mats-claassen working on creating the cocoapod and uploading it now

**Comment by mats-claassen** [comment]
Tell me if you need help with something

**Comment by Smiller193** [comment]
@mats-claassen I am having trouble creating the podspec file
https://stackoverflow.com/questions/53218959/invalid-videorow-podspec-file-undefined-method-join-for-tlphotopickerstr

**Comment by mats-claassen** [comment]
I saw you fixed that. I opened a first issue in the [VideoRow](https://github.com/EurekaCommunity/VideoRow) repository. We can continue the discussion about this row in that repository.
