### ISSUE TITLE
Disabled property not working

### ISSUE THREAD

**Issue by mirnpnh** [EurekaCommunity/ImageRow#56]
Hi,
Thanks for great library, It seems this component doesn't respects disabled property at all. If you set the disabled to true you can still choose picture by clicking on it. It would be nice if there was a greyish kind of color too when disabled.

Thanks in advance

**Comment by mats-claassen** [comment]
Hi @Innomalist This worked fine for me in the examples. If you set it in the initialiazer then it is enough to do `row.disabled = true`. If you set it later then do: 

```swift
    row.disabled = true
    row.evaluateDisabled()
```

**Comment by mirnpnh** [comment]
Alright thanks for response
