### ISSUE TITLE
Cocoapods failed to install ImageRow 4.0 (already have Eureka 5.0)

### ISSUE THREAD

**Issue by gangfang** [EurekaCommunity/ImageRow#65]
I tried to install the latest ImageRow with `pod 'ImageRow', '~> 4.0'` in installation instruction and failed. 

Below is the error message:
```
[!] CocoaPods could not find compatible versions for pod "ImageRow":
  In Podfile:
    ImageRow (~> 4.0)

None of your spec sources contain a spec satisfying the dependency: `ImageRow (~> 4.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

For now if anyone faces the same issue, you can use `pod 'ImageRow', :git => 'https://github.com/EurekaCommunity/ImageRow.git'`, which works for me.

**Comment by sahibhussain** [comment]
pod 'ImageRow', '~> 4.0'

**Comment by martheli** [comment]
pod 'ImageRow', '~> 4.0' does not work. I am also having the issue with ImageRow working with Eureka 5.0.

**Comment by mats-claassen** [comment]
4.0.0 has been released. It should work now 🚀
