### ISSUE TITLE
Constraint issue

### ISSUE THREAD

**Issue by IssaMansour** [EurekaCommunity/ImageRow#68]
Hello,

I'm using ImageRow 4.0, Xcode 10.2.1 with Swift 5.
I have a simple controller with only one ImageRow cell.
When I tapped on the cell, the picker is showing but I have a constraint issue:
```
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600001ad7a70 UIView:0x7fb050c97960.width == - 16   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600001ad7a70 UIView:0x7fb050c97960.width == - 16   (active)>
```

Here the code:
```
form
        +++ Section("sectionId")
            <<< ImageRow("id") { row in
                row.title = "Title"
                row.sourceTypes = [.All]
                row.clearAction = .yes(style: UIAlertAction.Style.destructive)
            }
```

**Comment by sahibhussain** [comment]
Same issue with me 

and also if you click on cancel the second time when you have an image selected the image going on left above the title.

**Comment by rodriar** [comment]
Hi there, the issue with the constraint seems to be an internal problem with UIKit. I did fix the issue with the image going to the left.

Cheers!

**Comment by ysong4** [comment]
Same issue with me.

**Comment by sahibhussain** [comment]
i think there is something wrong with updating cell as when stop any updateCell customisation the problem solves itself

**Comment by PierreBrisorgueil** [comment]
Same issue, anyone have find a temporary solution ?

**Comment by IssaMansour** [comment]
It's an iOS issue: https://stackoverflow.com/questions/55372093/uialertcontrollers-actionsheet-gives-constraint-error-on-ios-12-2-12-3
