### ISSUE TITLE
Creating an image format with an unknown type is an error

### ISSUE THREAD

**Issue by sa7bi** [EurekaCommunity/ImageRow#7]
Hi,
I have this weird problem when selecting an image from the Photo Library
`[Generic] Creating an image format with an unknown type is an error`

* My simplified code :

````swift
           +++ Section() { section in
                let header = createHeader(label: "Pictures or it didn't happend")
                section.header = header
                section.footer = createFooter()
            }
            <<< ImageRow() { row in
                row.tag = "image1"
                row.title = "Image 1"
                row.sourceTypes = .PhotoLibrary
                row.clearAction = .yes(style: UIAlertActionStyle.destructive)
                row.add(rule: RuleRequired())
                row.validationOptions = .validatesOnChange
            }
````
- Environment: Eureka : 2.0.0-beta.1,  ImageRow: 1.0, Xcode : 8.2.1 (8C1002), iOS: 10

Thanks for your help,
Sahbi

**Comment by sa7bi** [comment]
Ok,
I've found a fix. The problem seems not related to the Eureka-library but rather with Xcode. I've stopped Xcode from logging everything and now, weirdly enough, everything works correctly.

<img width="898" alt="capture d ecran 2017-01-15 09 10 38" src="https://cloud.githubusercontent.com/assets/544079/21961185/2c86c430-db03-11e6-8861-93bdc4730a40.png">

**Comment by derekgould** [comment]
I have the same problem ("unknown type"). Xcode 8.3.3. Any solution?
