### ISSUE TITLE
Camera as source type is NOT working

### ISSUE THREAD

**Issue by jzinkovich** [EurekaCommunity/ImageRow#72]
I am using Eureka version 5.0.0 and ImageRow version 4.0.0 when I add this to my form

 <<< ImageRow(FormItems.image) { row in
                row.title = "Item Image"
                row.sourceTypes = [.PhotoLibrary, .Camera]
                row.clearAction = .yes(style: UIAlertAction.Style.destructive)
            }

When I click on "Item Image" it doesn't present me with a menu of either photo library or using my camera it just takes me directly into my photo library?  Also when I remove .PhotoLibrary from sourceTypes and just leave .Camera it doesn't work.  I cannot get my camera to show up as an option.  In my plist I have camera access granted as other screens in my app are already integrating with the camera just fine but not using ImageRow to do so.

Before submitting issues ...

- Make sure you are using ImageRow's [latest release](https://github.com/xmartlabs/ImageRow/releases) or master branch version.
- Make sure your Xcode version is the latest stable one.
- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/ImageRow/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: ImageRow, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

**Comment by tejaskdubal** [comment]
What you are using simulator or real device?

**Comment by mats-claassen** [comment]
Closing due to lack of response
