### ISSUE TITLE
Cell's Accessory Type is not shown properly

### ISSUE THREAD

**Issue by hakan-niflioglu** [EurekaCommunity/ImageRow#77]
Hello, I am using Xcode 11.3, ImageRow 4.0, Swift 5.

I have a form with one section and inside it there is an ImageRow:

```Swift
ImageRow() { row in
            row.title = "Image"
            row.sourceTypes = .All
            row.clearAction = .yes(style: .destructive)
            row.tag = "TestImage"
        }.cellUpdate({ (cell, row) in
            cell.accessoryType = .disclosureIndicator
        })
```

I modify the cell's accessoryType to .disclosureIndicator for TextRow, DateRow, TimeRow successfully (I modified just to test it) but only ImageRow does not show .disclosureIndicator properly when running the app. Thank you in advance.

**Comment by mats-claassen** [comment]
ImageRow uses the `accessoryView` to show the chosen image. Therefore `accessoryType` is ignored.

**Comment by hakan-niflioglu** [comment]
Thank you @mats-claassen! 😊
