### ISSUE TITLE
Adding support for SPM

### ISSUE THREAD

**Issue by andrey-zelenin** [EurekaCommunity/ImageRow#80]
Xcode 11 allows adding swift packages very easily. Have you thought about adding SPM support?

**Comment by funkenstrahlen** [comment]
I created a PR with the required changes: #81

**Comment by andrey-zelenin** [comment]
I see changes in master, thanks

**Comment by funkenstrahlen** [comment]
@andrey-zelenin Can you please close this issue as it has been resolved?

**Comment by andrey-zelenin** [comment]
@funkenstrahlen, done
